/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/auth/mobile/login": {
    /** Mobile app login - returns JWT tokens */
    post: {
      requestBody: {
        content: {
          "application/json": {
            /**
             * Format: email
             * @example test@example.com
             */
            email: string;
            /**
             * Format: password
             * @example password123
             */
            password: string;
          };
        };
      };
      responses: {
        /** @description Login successful */
        200: {
          content: {
            "application/json": {
              /**
               * @description JWT access token for API requests
               * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
               */
              accessToken: string;
              /**
               * Format: uuid
               * @description Refresh token for obtaining new access tokens
               * @example 19706212-c220-465e-a94f-b3042ceb47ba
               */
              refreshToken: string;
              user: components["schemas"]["User"];
              /**
               * @description Access token lifetime in seconds
               * @example 3600
               */
              expiresIn: number;
            };
          };
        };
        /** @description Missing email or password */
        400: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Invalid credentials */
        401: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/api/auth/register": {
    /** Register a new user account */
    post: {
      requestBody: {
        content: {
          "application/json": {
            /**
             * Format: email
             * @example newuser@example.com
             */
            email: string;
            /**
             * Format: password
             * @example securepassword123
             */
            password: string;
          };
        };
      };
      responses: {
        /** @description User created successfully */
        201: {
          content: {
            "application/json": {
              /** @example User created successfully */
              message: string;
              user: components["schemas"]["User"];
            };
          };
        };
        /** @description Invalid input (bad email format or weak password) */
        400: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description User already exists */
        409: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/api/books": {
    /** Get all books (paginated and sortable) */
    get: {
      parameters: {
        query?: {
          /** @description Page number */
          page?: number;
          /** @description Items per page */
          limit?: number;
          /** @description Sort order (title, author, narrator, or series) */
          sort?: "title" | "author" | "narrator" | "series";
        };
      };
      responses: {
        /** @description Paginated list of books */
        200: {
          content: {
            "application/json": {
              books: components["schemas"]["Book"][];
              pagination: {
                /** @example 1 */
                page: number;
                /** @example 20 */
                limit: number;
                /** @example 150 */
                total: number;
                /** @example 8 */
                pages: number;
              };
            };
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Server error */
        500: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/api/books/{id}": {
    /** Get book details */
    get: {
      parameters: {
        query?: {
          /** @description Include related data (chapters) */
          include?: "chapters";
        };
        path: {
          /** @description Book ID */
          id: string;
        };
      };
      responses: {
        /** @description Book details */
        200: {
          content: {
            "application/json": components["schemas"]["Book"];
          };
        };
        /** @description Book not found */
        404: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/api/books/{id}/chapters": {
    /** Get chapters for a book (lazy extraction from audio file) */
    get: {
      parameters: {
        path: {
          /** @description Book ID */
          id: string;
        };
      };
      responses: {
        /** @description List of chapters */
        200: {
          content: {
            "application/json": {
              chapters: components["schemas"]["Chapter"][];
              /**
               * @description Where chapters came from:
               * - database: Previously extracted chapters from DB
               * - extracted: Newly extracted from audio file
               * - none: No chapters found in audio file
               * - unavailable: ffprobe not installed (graceful degradation)
               * - error: Extraction failed
               *
               * @example database
               * @enum {string}
               */
              source: "database" | "extracted" | "none" | "unavailable" | "error";
              /** @example No chapters found in audio file */
              message?: string | null;
            };
          };
        };
        /** @description Book not found */
        404: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/api/progress": {
    /** Get user progress for a book */
    get: {
      parameters: {
        query: {
          /** @description Book ID to get progress for */
          bookId: string;
        };
      };
      responses: {
        /** @description User progress */
        200: {
          content: {
            "application/json": {
              /**
               * Format: double
               * @example 3612.5
               */
              positionSeconds: number;
              /** @example false */
              completed: boolean;
              /**
               * Format: date-time
               * @example 2025-12-25T10:30:00Z
               */
              lastPlayed?: string | null;
            };
          };
        };
        /** @description Missing book ID */
        400: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    /** Mark book as completed or reset to not started */
    put: {
      requestBody: {
        content: {
          "application/json": {
            /** Format: uuid */
            bookId: string;
            /**
             * @description Mark as completed or reset progress
             * @enum {string}
             */
            status: "completed" | "not-started";
          };
        };
      };
      responses: {
        /** @description Progress status updated */
        200: {
          content: {
            "application/json": {
              /**
               * Format: double
               * @example 0
               */
              positionSeconds: number;
              /** @example true */
              completed: boolean;
              /**
               * Format: date-time
               * @example 2025-12-25T10:30:00Z
               */
              lastPlayed?: string | null;
            };
          };
        };
      };
    };
    /**
     * Update user progress (save position)
     * @description **Supports both authentication methods**:
     * - Session cookies (web)
     * - Bearer token (mobile)
     */
    post: {
      requestBody: {
        content: {
          "application/json": {
            /** Format: uuid */
            bookId: string;
            /** Format: double */
            positionSeconds: number;
            /**
             * Format: date-time
             * @description Optional client timestamp for conflict resolution
             */
            timestamp?: string;
          };
        };
      };
      responses: {
        /** @description Progress updated */
        200: {
          content: {
            "application/json": {
              /**
               * Format: double
               * @example 3612.5
               */
              positionSeconds: number;
              /** @example false */
              completed: boolean;
              /**
               * Format: date-time
               * @example 2025-12-25T10:30:00Z
               */
              lastPlayed: string;
              /**
               * @description Whether update was applied (false if timestamp conflict)
               * @example true
               */
              updated: boolean;
            };
          };
        };
      };
    };
  };
  "/api/search": {
    /** Search across books, authors, narrators, and series */
    get: {
      parameters: {
        query: {
          /** @description Search query string */
          q: string;
          page?: number;
          limit?: number;
          /** @description Comma-separated list of fields to return (optional) */
          fields?: string;
        };
      };
      responses: {
        /** @description Search results */
        200: {
          content: {
            "application/json": {
              results: components["schemas"]["Book"][];
              pagination: {
                page: number;
                limit: number;
                total: number;
                pages: number;
              };
            };
          };
        };
        /** @description Missing or invalid search query */
        400: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/api/browse/authors": {
    /** List all authors with book counts */
    get: {
      parameters: {
        query?: {
          page?: number;
          limit?: number;
        };
      };
      responses: {
        /** @description Paginated list of authors */
        200: {
          content: {
            "application/json": {
              results: components["schemas"]["AuthorWithBookCount"][];
              pagination: {
                page: number;
                limit: number;
                total: number;
                pages: number;
              };
            };
          };
        };
      };
    };
  };
  "/api/browse/series": {
    /** List all series with book counts */
    get: {
      parameters: {
        query?: {
          page?: number;
          limit?: number;
        };
      };
      responses: {
        /** @description Paginated list of series */
        200: {
          content: {
            "application/json": {
              results: components["schemas"]["SeriesWithBookCount"][];
              pagination: {
                page: number;
                limit: number;
                total: number;
                pages: number;
              };
            };
          };
        };
      };
    };
  };
  "/api/browse/narrators": {
    /** List all narrators with book counts */
    get: {
      parameters: {
        query?: {
          page?: number;
          limit?: number;
        };
      };
      responses: {
        /** @description Paginated list of narrators */
        200: {
          content: {
            "application/json": {
              results: components["schemas"]["NarratorWithBookCount"][];
              pagination: {
                page: number;
                limit: number;
                total: number;
                pages: number;
              };
            };
          };
        };
      };
    };
  };
  "/api/browse/categories": {
    /** List all categories with book counts */
    get: {
      parameters: {
        query?: {
          page?: number;
          limit?: number;
        };
      };
      responses: {
        /** @description Paginated list of categories */
        200: {
          content: {
            "application/json": {
              results: components["schemas"]["CategoryWithBookCount"][];
              pagination: {
                page: number;
                limit: number;
                total: number;
                pages: number;
              };
            };
          };
        };
      };
    };
  };
  "/api/authors/{id}": {
    /** Get author details and their books */
    get: {
      parameters: {
        query?: {
          page?: number;
          limit?: number;
        };
        path: {
          /** @description Author ID */
          id: string;
        };
      };
      responses: {
        /** @description Author with their books */
        200: {
          content: {
            "application/json": {
              /** Format: uuid */
              id: string;
              /** @example Patrick Rothfuss */
              name: string;
              asin?: string | null;
              books: components["schemas"]["Book"][];
              pagination: components["schemas"]["Pagination"];
            };
          };
        };
        /** @description Author not found */
        404: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/api/series/{id}": {
    /** Get series details and books in the series */
    get: {
      parameters: {
        query?: {
          page?: number;
          limit?: number;
        };
        path: {
          /** @description Series ID */
          id: string;
        };
      };
      responses: {
        /** @description Series with books */
        200: {
          content: {
            "application/json": {
              /** Format: uuid */
              id: string;
              /** @example The Kingkiller Chronicle */
              title: string;
              asin?: string | null;
              books: components["schemas"]["Book"][];
              pagination: components["schemas"]["Pagination"];
            };
          };
        };
        /** @description Series not found */
        404: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/api/narrators/{id}": {
    /** Get narrator details and their books */
    get: {
      parameters: {
        query?: {
          page?: number;
          limit?: number;
        };
        path: {
          /** @description Narrator ID */
          id: string;
        };
      };
      responses: {
        /** @description Narrator with their books */
        200: {
          content: {
            "application/json": {
              /** Format: uuid */
              id: string;
              /** @example Nick Podehl */
              name: string;
              asin?: string | null;
              books: components["schemas"]["Book"][];
              pagination: components["schemas"]["Pagination"];
            };
          };
        };
        /** @description Narrator not found */
        404: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/api/categories/{id}": {
    /** Get category details and books in the category */
    get: {
      parameters: {
        query?: {
          page?: number;
          limit?: number;
        };
        path: {
          /** @description Category ID */
          id: string;
        };
      };
      responses: {
        /** @description Category with books */
        200: {
          content: {
            "application/json": {
              /** Format: uuid */
              id: string;
              /** @example Fantasy */
              name: string;
              level?: number;
              books: components["schemas"]["Book"][];
              pagination: components["schemas"]["Pagination"];
            };
          };
        };
        /** @description Category not found */
        404: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/api/library": {
    /** Get user's library books */
    get: {
      responses: {
        /** @description User's library */
        200: {
          content: {
            "application/json": {
              books: components["schemas"]["Book"][];
              /** @example 42 */
              total: number;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    /** Add book to user's library */
    post: {
      requestBody: {
        content: {
          "application/json": {
            /** Format: uuid */
            bookId: string;
          };
        };
      };
      responses: {
        /** @description Book already in library */
        200: {
          content: {
            "application/json": {
              /** @example Book already in library */
              message: string;
            };
          };
        };
        /** @description Book added to library */
        201: {
          content: {
            "application/json": {
              /** @example Book added to library */
              message: string;
            };
          };
        };
        /** @description Missing book ID */
        400: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/api/library/{bookId}": {
    /** Remove book from user's library */
    delete: {
      parameters: {
        path: {
          /** @description Book ID to remove */
          bookId: string;
        };
      };
      responses: {
        /** @description Book removed from library */
        200: {
          content: {
            "application/json": {
              /** @example Book removed from library */
              message: string;
            };
          };
        };
        /** @description Library not found */
        404: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Error: {
      /**
       * @description Error message
       * @example Book not found
       */
      error: string;
    };
    Pagination: {
      /** @example 1 */
      page: number;
      /** @example 20 */
      limit: number;
      /** @example 150 */
      total: number;
      /**
       * @description Total number of pages
       * @example 8
       */
      pages: number;
    };
    Book: {
      /**
       * Format: uuid
       * @example 550e8400-e29b-41d4-a716-446655440000
       */
      id: string;
      /** @example B002V5D1CG */
      asin: string;
      /** @example The Name of the Wind */
      title: string;
      /** @example Told in Kvothe's own voice, this is the tale of the magically gifted young man... */
      description?: string | null;
      /** @example 1068 */
      runtimeMinutes: number;
      /**
       * Format: date
       * @example 2008-04-01
       */
      releaseDate?: string | null;
      /** @example DAW */
      publisher?: string | null;
      /**
       * Format: uri
       * @example https://book-vault-media.s3.amazonaws.com/covers/B002V5D1CG.jpg
       */
      coverUrl: string;
      /**
       * Format: uri
       * @example https://book-vault-media.s3.amazonaws.com/audio/B002V5D1CG.m4b
       */
      audioUrl: string;
      authors: components["schemas"]["Author"][];
      narrators?: components["schemas"]["Narrator"][];
      series?: components["schemas"]["SeriesInfo"][];
      categories?: components["schemas"]["Category"][];
    };
    Author: {
      /** Format: uuid */
      id: string;
      /** @example Patrick Rothfuss */
      name: string;
      /** @example B002BMAYSQ */
      asin?: string | null;
    };
    Narrator: {
      /** Format: uuid */
      id: string;
      /** @example Nick Podehl */
      name: string;
      asin?: string | null;
    };
    SeriesInfo: {
      /** Format: uuid */
      id: string;
      /** @example The Kingkiller Chronicle */
      title: string;
      /**
       * @description Book number in series (can be '1', '1.5', 'Prequel', etc.)
       * @example 1
       */
      sequence?: string | null;
      asin?: string | null;
    };
    Category: {
      /** Format: uuid */
      id: string;
      /** @example Fantasy */
      name: string;
    };
    Chapter: {
      /** Format: uuid */
      id: string;
      /** @example Chapter 1: A Place for Demons */
      title: string;
      /**
       * Format: double
       * @example 0
       */
      startTime: number;
      /**
       * Format: double
       * @example 1806.5
       */
      endTime: number;
      /** @example 0 */
      index: number;
    };
    UserProgress: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      bookId: string;
      /** Format: uuid */
      userId: string;
      /**
       * Format: double
       * @example 3612.5
       */
      positionSeconds: number;
      /** @example false */
      completed: boolean;
      /**
       * Format: date-time
       * @example 2025-12-25T10:30:00Z
       */
      lastPlayed: string;
    };
    User: {
      /** Format: uuid */
      id: string;
      /**
       * Format: email
       * @example user@example.com
       */
      email: string;
    };
    AuthorWithBookCount: {
      /** Format: uuid */
      id: string;
      /** @example Patrick Rothfuss */
      name: string;
      /** @example B002BMAYSQ */
      asin?: string | null;
      /** @example 12 */
      bookCount: number;
    };
    Series: {
      /** Format: uuid */
      id: string;
      /** @example The Kingkiller Chronicle */
      title: string;
      asin?: string | null;
    };
    SeriesWithBookCount: {
      /** Format: uuid */
      id: string;
      /** @example The Kingkiller Chronicle */
      title: string;
      asin?: string | null;
      /** @example 3 */
      bookCount: number;
    };
    NarratorWithBookCount: {
      /** Format: uuid */
      id: string;
      /** @example Nick Podehl */
      name: string;
      asin?: string | null;
      /** @example 25 */
      bookCount: number;
    };
    CategoryWithBookCount: {
      /** Format: uuid */
      id: string;
      /** @example Fantasy */
      name: string;
      /** @example 1 */
      level?: number;
      /** @example 150 */
      bookCount: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
