// Base entity types (matching Prisma models but serializable for client components)

/**
 * Author entity representing an audiobook author.
 * Matches Prisma Author model but serialized for client use.
 */
export interface Author {
  /** UUID generated by Prisma */
  id: string;

  /** Author's full name as appears on book cover */
  name: string;

  /** Amazon Standard Identification Number from Audible, used for linking */
  asin?: string | null;

  /** Timestamp when author was first added to database */
  createdAt?: Date | string;
}

/**
 * Narrator entity representing an audiobook narrator/voice actor.
 * Matches Prisma Narrator model but serialized for client use.
 */
export interface Narrator {
  /** UUID generated by Prisma */
  id: string;

  /** Narrator's full name */
  name: string;

  /** Amazon Standard Identification Number from Audible */
  asin?: string | null;

  /** Timestamp when narrator was first added to database */
  createdAt?: Date | string;
}

/**
 * Series entity representing a collection of related books.
 * Matches Prisma Series model but serialized for client use.
 */
export interface Series {
  /** UUID generated by Prisma */
  id: string;

  /** Series title (e.g., "Harry Potter", "The Lord of the Rings") */
  title: string;

  /** Amazon Standard Identification Number from Audible */
  asin?: string | null;

  /** Timestamp when series was first added to database */
  createdAt?: Date | string;
}

/**
 * Category/Genre entity for organizing books by topic or genre.
 * Matches Prisma Category model.
 */
export interface Category {
  /** UUID generated by Prisma */
  id: string;

  /** Category name (e.g., "Science Fiction", "Mystery", "History") */
  name: string;
}

/**
 * SeriesInfo extends Series with sequence number from the BookSeries join table.
 * Used when displaying a book's series membership with its position in the series.
 */
export interface SeriesInfo {
  /** UUID of the series */
  id: string;

  /** Series title */
  title: string;

  /** Amazon Standard Identification Number */
  asin?: string | null;

  /** Book's position in series (e.g., 1 for first book, 2 for second). Null if position unknown. */
  sequence?: number | null;
}

/**
 * Complete book entity with all metadata and relationships.
 * Transformed from Prisma Book model with presigned URLs and flattened relations.
 * This is the primary book type used throughout the application.
 */
export interface Book {
  /** UUID generated by Prisma */
  id: string;

  /** Amazon Standard Identification Number - unique identifier from Audible */
  asin: string;

  /** Book title as it appears on cover */
  title: string;

  /**
   * Audio availability (S3 Intelligent-Tiering):
   * available = streamable now; archived = needs a ~3-5h restore;
   * restoring = restore in progress. Drives list badges + detail-page CTA.
   * Optional for backward compatibility with pre-restore backends — treat
   * absent as 'available'.
   */
  archiveStatus?: 'available' | 'archived' | 'restoring';

  /** Publisher's marketing description in Markdown format (converted from HTML) */
  publisherSummary?: string | null;

  /** Total audiobook length in minutes */
  runtimeMinutes?: number | null;

  /** Original release date in ISO 8601 format (YYYY-MM-DD) */
  releaseDate?: Date | string | null;

  /** Publisher name (e.g., "Audible Studios", "Random House Audio") */
  publisher?: string | null;

  /** Presigned S3 URL (production) or local API URL (dev) to cover image */
  coverUrl: string | null;

  /** Presigned S3 URL (production) or local API URL (dev) to audio file */
  audioUrl: string | null;

  /** Array of authors who wrote this book */
  authors: Author[];

  /** Array of narrators who performed this audiobook */
  narrators: Narrator[];

  /** Array of series this book belongs to, with sequence numbers */
  series: SeriesInfo[];

  /** Array of categories/genres this book is tagged with */
  categories?: Category[];

  /** Additional metadata from Libation import (JSON field). May include reviews, product details, etc. */
  metadata?: Record<string, unknown>;
}

/**
 * Pagination metadata for paginated API responses.
 * Follows standard pagination pattern with page numbers and totals.
 */
export interface Pagination {
  /** Current page number (1-indexed) */
  page: number;

  /** Maximum items per page requested */
  limit: number;

  /** Total number of items across all pages */
  total: number;

  /** Total number of pages available */
  pages: number;
}

/**
 * Standard response format for book list endpoints.
 * Used by /api/books and other endpoints that return multiple books.
 */
export interface BooksResponse {
  /** Array of books for current page */
  books: Book[];

  /** Pagination metadata */
  pagination: Pagination;
}

/**
 * Response format for search endpoints.
 * Extends BooksResponse with the search query for context.
 */
export interface SearchResponse {
  /** The search query string that was executed */
  query: string;

  /** Array of matching books */
  books: Book[];

  /** Pagination metadata */
  pagination: Pagination;
}

/**
 * Author entity with paginated books they've written.
 * Used by /api/authors/[id] endpoint.
 */
export interface AuthorWithBooks extends Author {
  /** Array of books authored by this author */
  books: Book[];

  /** Pagination metadata for books list */
  pagination: Pagination;
}

/**
 * Narrator entity with paginated books they've narrated.
 * Used by /api/narrators/[id] endpoint.
 */
export interface NarratorWithBooks extends Narrator {
  /** Array of books narrated by this narrator */
  books: Book[];

  /** Pagination metadata for books list */
  pagination: Pagination;
}

/**
 * Series entity with paginated books in the series.
 * Books are ordered by sequence number.
 * Used by /api/series/[id] endpoint.
 */
export interface SeriesWithBooks extends Series {
  /** Array of books in this series, ordered by sequence */
  books: Book[];

  /** Pagination metadata for books list */
  pagination: Pagination;
}

/**
 * Author with book count for browse/listing pages.
 * Used by /api/browse/authors to show all authors with how many books each has.
 */
export interface AuthorBrowseItem extends Author {
  /** Prisma count aggregation with number of books */
  _count: { books: number };
}

/**
 * Narrator with book count for browse/listing pages.
 * Used by /api/browse/narrators.
 */
export interface NarratorBrowseItem extends Narrator {
  /** Prisma count aggregation with number of books */
  _count: { books: number };
}

/**
 * Series with book count for browse/listing pages.
 * Used by /api/browse/series.
 */
export interface SeriesBrowseItem extends Series {
  /** Prisma count aggregation with number of books */
  _count: { books: number };
}

/**
 * Category with book count for browse/listing pages.
 * Used by /api/browse/categories.
 */
export interface CategoryBrowseItem extends Category {
  /** Prisma count aggregation with number of books */
  _count: { books: number };
}
